removed rst_node.py:38: DeprecationWarning: ImplicitNode.__init__ missing 1 required positional argument: 'body'. This will become an error in Python 3.15.